"""debugging hashed passwored

Revision ID: 957437a26834
Revises: 6d990fbba7ab
Create Date: 2025-03-16 10:00:33.072810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '957437a26834'
down_revision = '6d990fbba7ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)

    # ### end Alembic commands ###
